version: "3.8"

services:
    backend:
        container_name: questapp-backend
        build:
            context: ./backend
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            HOST: 127.0.0.1
            USERNAME: questapp
            PASSWORD: Password!
            DB_PORT: 3306
            SECRET: VerySecure
            TZ: Z

    frontend:
        container_name: questapp-frontend
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        environment:
            PUBLIC_BASE_URL: http://192.168.1.210:8080
