version: "3.3"
services:
    db:
        # Building is required (or run init scripts on your own)
        image: questapp-mysql:0.1.0
        restart: always
        environment:
            MYSQL_DATABASE: "db"
            # So you don't have to use root, but you can if you like
            MYSQL_USER: "questapp"
            # You can use whatever password you like
            MYSQL_PASSWORD: "Password!"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "Password!"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql
        networks:
            - mysql-phpmyadmin

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:5.2.1
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: Password!
        networks:
            - mysql-phpmyadmin

networks:
    mysql-phpmyadmin:

volumes:
    my-db:
