name: Backend & Frontend Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    backend-tests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Build MySQL Image
              run: make build_db_image
              working-directory: .
            - name: Run MySQL Image
              run: make run_db_image
              working-directory: .
            - name: Install dependencies
              run: yarn install --immutable --immutable-cache --check-cache
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Copy .env file
              run: cp .env.sample .env
            - name: Run Playwright tests
              run: |
                  yarn start &
                  sleep 3
                  npx playwright test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30

    frontend-tests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Build MySQL Image
              run: make build_db_image
              working-directory: .
            - name: Run MySQL Image
              run: make run_db_image
              working-directory: .
            - name: Install dependencies
              run: |
                  yarn install --immutable --immutable-cache --check-cache
                  cd ../backend
                  yarn install --immutable --immutable-cache --check-cache
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Copy .env file
              run: cp .env.sample .env
              working-directory: ./backend
            - name: Copy .env file
              run: cp .env.sample .env
              working-directory: ./frontend
            - name: Run Server
              run: yarn start &
              working-directory: ./backend
            - name: Run Playwright tests
              run: |
                  sleep 3
                  npx playwright test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
